name: Push Release and Tag

on: [ push ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: get release
        run: echo "current_release=$(<env/CURRENT_RELEASE)" >> $GITHUB_ENV

      - name: Get version
        run: echo 'The  selected version is' $current_release

      - name: Create Release
        id: create_release
        uses: idealdotcom/create-release@irlatest_v2 
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          release: ${current_release}
        with:
          tag_name: v${{ env.current_release }}
          release_name: v${{ env.current_release }}
          draft: false
          prerelease: false
          jira_username: ${{ secrets.JIRA_USERNAME }}
          jira_password: ${{ secrets.JIRA_PASSWORD }}

      - name: Get release again
        run: |
          echo "release_version: $RELEASE_TAG"

